[phases.setup]
# Use Node.js 20 from NixPkgs (Node 20.x)
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = [
  "yarn install --frozen-lockfile"
]

[phases.build]
cmds = [
  "yarn build"
]

[start]
# Launch both frontend and backend in parallel
cmd = "yarn start" 